### ISSUE TITLE
DTI Protocol 1.25 mm resolution

### ISSUE THREAD

**Issue by NeuroimagingOL** [CMRR-C2P/MB#235] opened 2019-10-01 13:31 UTC
Dear all,

we are running the MB sequence on our Siemens Prisma VE11C. Our goal is to measure DTI with a isotropic resolution of 1.25 mm.  For preprocessing of the data we use FSL (5.0.9). Images were processed using topup and eddy, and registered to the T1 image using epi_reg (grey-white boundary of the structural image seen in red). Afterwards, the diffusion tensor model was fit using dtifit.  

We still have some artefacts in our images which we have no solution for. Does anybody of you have an idea what causes these artefacts or how to avoid them?

Attached we have the protocol which we used as pdf, as well as some images of the artefacts.

We would be very thankful about any comments or hints.

Best regards,
Tina and Melanie

![artifacts_new](https://user-images.githubusercontent.com/55829413/65966423-5c6ab080-e460-11e9-92a1-2e27a6640557.png)
![artifacts2](https://user-images.githubusercontent.com/55829413/65966424-5c6ab080-e460-11e9-94f1-10e0adb85f88.png)
[MELANI~1.PDF](https://github.com/CMRR-C2P/MB/files/3676453/MELANI.1.PDF)

**Comment by BenInglis** [comment] 2019-10-01 17:36
Guys, could you please elaborate on the nature of the artifacts, and perhaps mark up the images to highlight those of concern? I see some potential regions of dropout, I see some distortions not fixed by TOPUP, but no glaring problems. What am I missing? 

If you could also post an example of the raw data, maybe a link to a full set, that could help a lot, too.
Cheers!
Ben

**Comment by NeuroimagingOL** [comment] 2019-10-07 10:12
Hi Ben,

thanks a lot for your quick response. We uploaded a raw data here: https://drive.google.com/file/d/1-7llc-X2MSKIThusgslag-qKKWAZOTxF/view?usp=sharing

If you have any problems to get the data, please let us know.

We also included some images with arrows pointing towards the artefacts.

Thanks a lot for your help,
Best regards,
Tina and Melanie
![B0_artefact 1](https://user-images.githubusercontent.com/55829413/66303597-a689e100-e8fb-11e9-841a-0b7053102e00.png)
![B0raw_artefact 1](https://user-images.githubusercontent.com/55829413/66303602-ae498580-e8fb-11e9-9382-10faed958d3b.png)

**Comment by BenInglis** [comment] 2019-10-07 12:58
Ah sorry, I meant the raw dicoms as they come off the scanner. Converting the file format may change the dynamic range, which makes it more difficult to differentiate between scanner and subsequent software issues. The SNR looks strange in the nifti viewer, but that may be the nifti viewer. I'd like to check that there are no artificially inflated regions of dropout arising from mechanical resonances or eddy currents causing signal loss with the use of partial Fourier. (This is well known.)

You are indicating regions where residual problems with distortion, which will be quite high with relatively low bandwidth, long echo spacing (0.73 ms) readout, wouldn't be a surprise. The TOPUP method is only an approximation to a true field map, and even a true field map has limits in its ability to relocate properly pixels that have coalesced.

**Comment by NeuroimagingOL** [comment] 2019-10-08 09:07
Sorry for the misunderstanding. Here are the dicoms: https://drive.google.com/file/d/1RX-cb09uD29KFlq89VBznC_A0-5z8iqZ/view

**Comment by BenInglis** [comment] 2019-10-08 20:47
Did this subject have corrective lenses? Apart from a slight asymmetry in the frontal lobe distortions that might have arisen from corrective lenses, or simply from the shape of the person's skull, I don't see anything unexpected. Which suggests to me that you are at, or slightly beyond, the capabilities of the scanner. I don't recall seeing DWI at (1.25 mm)^3 resolution at 3 T. To get such high in-plane resolution has required a low bandwidth (1510 Hz) and relatively long echo spacing (0.73 ms), which has produced the strong distortion patterns you're seeing. The use of multiband has no effect on the restrictions in-plane; you'd have the same problem without MB if you drive to 1.25 mm x 1.25 mm in-plane. This would be worthwhile, to prove that the problem is in the physics, not in the sequence.

Since the 6/8ths partial Fourier is smoothing your resolution anyway - you're probably getting something closer to 1.5 mm in reality - have you considered reducing the resolution a bit, to see if you can reduce the echo spacing?

**Comment by NeuroimagingOL** [comment] 2019-10-09 09:05
Thanks for your evaluation of our images and the protocol.
The participant did not have corrective lenses.
Actually we tried to get the highest possible resolution therefore we decided for 1.25 since 1 mm was even worse or the sequence did not run at all. Thus, would you recommend to use the protocol as it is right now if we want to stick with the 1.25 mm? Or should we get rid of the 6/8 partial Fourier?

**Comment by mharms** [comment] 2019-10-09 13:58
Is this occurring in all subjects, or just this one subject?  Similar to @BenInglis I'm wondering if this isn't something particular to this one subject.

**Comment by BenInglis** [comment] 2019-10-09 16:04
> Thanks for your evaluation of our images and the protocol.
> The participant did not have corrective lenses.
> Actually we tried to get the highest possible resolution therefore we decided for 1.25 since 1 mm was even worse or the sequence did not run at all. Thus, would you recommend to use the protocol as it is right now if we want to stick with the 1.25 mm? Or should we get rid of the 6/8 partial Fourier?

If you turn off partial Fourier you'll need to enable GRAPPA to keep the TE reasonable. Since you're only using MB=2, GRAPPA with R=2 may be an acceptable total acceleration. You'll also halve the distortion level with R=2 GRAPPA. The trick is to ensure the auto-calibration scans (ACS) at the start of the acquisition are as motion-free as possible.

**Closed** 2021-02-10 01:35 UTC
