### ISSUE TITLE
Recon hanging on Prisma

### ISSUE THREAD

**Issue by HiroNakatani** [CMRR-C2P/MB#104] opened 2015-10-15 11:02 UTC
We have facing the similar issue with "Recon hanging on Prisma VD13D/R012b" posted on Sept 24.
We use MB-EPI R012 on a Prisma (VD13D).

Reconstruction process has been sometimes, but not always, stopped.
We looked in TWIX. The 'problem' scan showed "rip" for its state and "Error" for its status.
We would like to know how to solve this issue.
![twix](https://cloud.githubusercontent.com/assets/15140336/10511805/d6cd5c24-7376-11e5-821b-4e23e6ed23c5.png)

Sincerely yours,
Hironori Nakatani

**Comment by eauerbach** [comment] 2015-11-19 00:34
As far as we can tell, this is a Siemens problem, and it occurs just as often with product sequences when acquiring at high data rates. Of course the multi-band sequences are almost always being run at very high data rates, so it occurs more often when running multi-band. But there is no direct link and no solution; we have escalated this as high as possible within Siemens and they supposedly can't find anything either. Hopefully it is better in VE11.
duplicate of #102

**Closed by eauerbach** 2015-11-19 00:34 UTC
