### ISSUE TITLE
MB Recon slow down between R010c and R011a 

### ISSUE THREAD

**Issue by xjqian** [CMRR-C2P/MB#79] opened 2014-11-13 22:28 UTC
Recon slow down using MB-only protocol (MB=7, 2.1mm iso, 70 slices) observed on 3T Skyra (VD13A) between R010c and R011a. Suspect that the implementation of LeakBlock (even though not selected in protocol) in the ICE program leading to this slow down. Reported here as a place-holder and will double-check R012.

**Comment by eauerbach** [comment] 2015-05-21 22:21
Closing due to age/unconfirmed

**Closed by eauerbach** 2015-05-21 22:21 UTC
Labels: 0 - unconfirmed, vd13a
