### ISSUE TITLE
Prisma VD13D: After installation of R015 frequent but not reproducible reconstruction failure

### ISSUE THREAD

**Issue by claus-magdeburg** [CMRR-C2P/MB#153] opened 2017-03-08 14:04 UTC
Hello,

After having installed R015 yesterday, we had four independent occurrences of the error "Preparation of image reconstruction failed" although about five volumes had been reconstructed and saved successfully. Restarting the sequence has been successful in all four cases. We had never had similar incidents with R014, so it seems unlikely that this is a coincidence. Did anybody else make similar observations on a Prisma with VD 13D?

We do have a save log and we can provide the protocol details. Should we attach them to this forum or should we send them by email?

If the problem persists would it be possible to get R014 back for the time being?

Best wishes from Germany

Claus

Edit: Obviously we are not the only one having that problem, as RAWaggoner reported the exactly same issue just one minute before I did. RAWaggoner also attached a save log so that I assume that another savelog from my side is not necessary. Of course we can provide it if it is useful.

**Comment by swrieger** [comment] 2017-03-08 14:35
Dear all,

Same problem here in Oxford, errors since update are recurrent but not reliably reproducible.

An R014b with extended expiry date would be great, to save us having to cancel any more scanning slots until R015 can be patched.

Best wishes,

Seb

**Comment by bixente-Bordeaux** [comment] 2017-03-08 16:39
Hi everybody,

Same issue in Bordeaux. I agree with the two previous people that an extension of the R014 version would be of great help. 

All the best,

Bixente

**Comment by eauerbach** [comment] 2017-03-08 19:40
Duplicate of #152

**Closed by eauerbach** 2017-03-08 19:40 UTC
