### ISSUE TITLE
Banding and SNR

### ISSUE THREAD

**Issue by mworden** [CMRR-C2P/MB#99] opened 2015-07-24 18:00 UTC
I wasn't sure if this should be reported as a new issue or linked to the open issue on banding.  We are running version 012B on a Prisma Fit with release VD13D. 

We are seeing significant banding and also SNR inconsistencies across slices in MB BOLD EPI.  We haven't tried every combination of things but we see it with a multiband factor or 3 and of 4 at 1.5, 2 and 3 mm voxels both for interleaved and ascending slice orders.  TR for all test cases = 2000 ms.  At a factor of 2 the banding is not immediately apparent.  

We also see some curious SNR issues.  The raw SNR for the images seems to be lower for 3mm voxels than for 2mm voxels, whereas I would expect a substantial increase on the order of 27:8 for the larger voxels.  

Slice by slice variance also appears to be inconsistent with lower numbered slices tending to have substantially higher variances.  We see this both in phantom data and in brain data.

Attached is an image showing banding from a rather extensive analysis by one of our researchers.   I have a pdf document with lots of additional graphs and analysis that I am happy to pass along if you contact me by email at worden@brown.edu.

I would be grateful for your thoughts and any help you might be able to provide.  We have a number of users who are anxious to begin using multiband for their work but I don't feel like I can recommend it quite yet until we resolve these issues.

Thanks!
Mike Worden

![phantom_banding](https://cloud.githubusercontent.com/assets/13486241/8880823/9bcfc192-3209-11e5-8939-70903cb1def3.gif)

**Comment by eauerbach** [comment] 2015-07-28 21:38
marking as duplicate of issue #67

**Closed by eauerbach** 2015-07-28 21:38 UTC
