### ISSUE TITLE
XA30 certificate installation crash patch?

### ISSUE THREAD

**Issue by abfeld007** [CMRR-C2P/MB#326] opened 2023-08-01 17:08 UTC
Dear CMRR, our Siemens Skyra was affected by the bug affecting XA30, making the system unbootable (as referenced in the installation instructions). My research is completely dependent on the CMRR's multiband. Any update on the patch?

**Comment by eauerbach** [comment] 2023-08-11 17:08
I do not have any updates about the patch, Siemens claimed it would be available in July but obviously that appears to have been too optimistic.

**Comment by eauerbach** [comment] 2023-08-11 17:11
duplicate of #313

**Closed by eauerbach** 2023-08-11 17:11 UTC
