### ISSUE TITLE
Banding artifact in multiband fMRI

### ISSUE THREAD

**Issue by jczhuang** [CMRR-C2P/MB#91] opened 2015-03-04 01:07 UTC
Attached is an unprocessed (only dicom -> nii conversion and nothing else) multiband fMRI data set. The subject has little to no head motion. You can see 4 bands in brightness (we used 4x acceleration). It is also found in other similar human and phantom scans, and the related sbref images. 

The sequence is VD13D R012, BOLD. Our scanner model is Prisma Fit.

 Could you let us know if you have any idea or solution about this issue?

Thanks!
JC

![screen shot 2015-03-01 at 10 34 50 am](https://cloud.githubusercontent.com/assets/11304520/6475868/399dd992-c1c4-11e4-91a2-715450382ab8.png)

![phan150303d-sref_sag1](https://cloud.githubusercontent.com/assets/11304520/6476167/80609fb0-c1c7-11e4-9075-856f128063b9.png)

**Comment by xjqian** [comment] 2015-03-04 21:38
Please reopen issue #67

**Comment by eauerbach** [comment] 2015-07-28 21:37
marking as duplicate of issue #67

**Closed by eauerbach** 2015-07-28 21:37 UTC
